linreg <- read.table("BondNew.txt",header=TRUE)
x <- linreg$CouponRate
y <- linreg$BidPrice
N <- length(y)
linreg_dat <- list(N=N,y=y,x=x)
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
fit <- stan(file = 'linregmodel.stan', data = linreg_dat,
            iter = 9000, warmup=1000, thin = 2, chains = 4)
summary(fit,pars=c('beta0','beta1','sigma2'),)$summary #overall
summary(fit,pars=c('beta0','beta1','sigma2'),probs=c(.025,.975))$summary #only 95% prob interval
summary(fit,pars=c('beta0','beta1','sigma2'),probs=c(.025,.975))$c_summary # for each chain
draws <- as.array(fit,pars=c('beta0','beta1','sigma2'))
samps <- extract(fit)
names(samps)
chains <- cbind(samps[[1]],samps[[2]],samps[[5]])
colnames(chains) <- c('b0','b1','s2')
library(coda)
test <- As.mcmc.list(fit)
gelman.diag(test) #only works sometimes (Cholesky error)
dim(draws)
test1 <- as.mcmc(draws[1:4000,1,1])
test2 <- as.mcmc(draws[1:4000,2,1])
test3 <- as.mcmc(draws[1:4000,3,1])
test4 <- as.mcmc(draws[1:4000,4,1])
test <- list(test1,test2,test3,test4)
gelman.diag(test)
test1 <- as.mcmc(draws[1:4000,1,2])
test2 <- as.mcmc(draws[1:4000,2,2])
test3 <- as.mcmc(draws[1:4000,3,2])
test4 <- as.mcmc(draws[1:4000,4,2])
test <- list(test1,test2,test3,test4)
gelman.diag(test)
test1 <- as.mcmc(draws[1:4000,1,3])
test2 <- as.mcmc(draws[1:4000,2,3])
test3 <- as.mcmc(draws[1:4000,3,3])
test4 <- as.mcmc(draws[1:4000,4,3])
test <- list(test1,test2,test3,test4)
gelman.diag(test)
sims <- as.mcmc(chains)
raftery.diag(sims)
geweke.diag(sims)
autocorr.diag(sims)
effectiveSize(sims)
library(shinystan)
launch_shinystan(fit)
